-- 코드를 입력하세요
WITH TEMP AS(
SELECT A.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT A JOIN FOOD_ORDER B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID, PRODUCT_NAME)



SELECT PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES
FROM TEMP
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC