WITH RECURSIVE TEMP AS (
    SELECT ID, 1 AS LEVEL
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT CHILD.ID, PARENT.LEVEL+1
    FROM ECOLI_DATA CHILD JOIN TEMP PARENT
    ON CHILD.PARENT_ID = PARENT.ID
    
)

SELECT ID
FROM TEMP
WHERE LEVEL=3
ORDER BY ID ASC