WITH FRONT AS(
    SELECT SUM(CODE) CODES
    FROM SKILLCODES 
    WHERE CATEGORY='Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS 
WHERE SKILL_CODE & (SELECT CODES
                   FROM FRONT)
ORDER BY ID