SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M 
JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
JOIN (SELECT MEMBER_ID
      FROM REST_REVIEW
      GROUP BY MEMBER_ID
      ORDER BY COUNT(*) DESC
      LIMIT 1) AS BEST_MEMBER ON M.MEMBER_ID = BEST_MEMBER.MEMBER_ID
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC;