WITH CHILD AS (
    SELECT PARENT_ID, COUNT(*) CNT
    FROM ECOLI_DATA 
    GROUP BY PARENT_ID
)

# SELECT ID, 
# FROM ECOLI_DATA 

SELECT ID, 
    CASE WHEN (SELECT CNT
    FROM CHILD C
    WHERE E.ID=C.PARENT_ID) IS NULL THEN 0
    ELSE (SELECT CNT
    FROM CHILD C
    WHERE E.ID=C.PARENT_ID)
    END AS CHILD_COUNT
    
FROM ECOLI_DATA E
ORDER BY ID