-- 코드를 입력하세요
WITH TEMP AS (SELECT DISTINCT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, A.GENDER, B.USER_ID
FROM USER_INFO A JOIN ONLINE_SALE B
ON A.USER_ID=B.USER_ID
WHERE A.GENDER IS NOT NULL)

SELECT YEAR, MONTH, GENDER, COUNT(*)
FROM TEMP
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER