WITH TOTAL_SALE AS(
    SELECT *
    FROM ONLINE_SALE 
    
    UNION ALL
    
    SELECT OFFLINE_SALE_ID, NULL USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE 
)


SELECT SALES_DATE,	PRODUCT_ID,	USER_ID,	SALES_AMOUNT
FROM TOTAL_SALE
WHERE SALES_DATE LIKE "2022-03%"
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC