-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE*(100-C.DISCOUNT_RATE)/100*30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR A JOIN (SELECT *
                                   FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                                   WHERE DURATION_TYPE='30일 이상') C
ON A.CAR_TYPE=C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV')
AND NOT EXISTS (SELECT *
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
               WHERE B.CAR_ID=A.CAR_ID
               AND START_DATE<='2022-11-30' AND END_DATE>='2022-11-01')
AND A.DAILY_FEE*(100-C.DISCOUNT_RATE)/100*30 >=500000
AND A.DAILY_FEE*(100-C.DISCOUNT_RATE)/100*30 <2000000
ORDER BY FEE DESC, A.CAR_ID ASC, A.CAR_ID DESC

# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
# ON A.CAR_ID=B.CAR_ID
# WHERE A.CAR_TYPE IN ('세단', 'SUV')
# ORDER BY A.car_id, start_date