-- 코드를 작성해주세요
WITH NEW_FISH AS(
    SELECT ID, FISH_TYPE,
    CASE
        WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH
    END NEW_LENGTH
    FROM FISH_INFO 
)

SELECT COUNT(*) FISH_COUNT, MAX(NEW_LENGTH) MAX_LENGTH, FISH_TYPE
FROM NEW_FISH 
GROUP BY FISH_TYPE
HAVING AVG(NEW_LENGTH)>=33
ORDER BY FISH_TYPE ASC