SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO A
WHERE A.REST_ID =
        (SELECT REST_ID
        FROM REST_INFO B
        WHERE B.FOOD_TYPE=A.FOOD_TYPE
        ORDER BY FAVORITES DESC
        LIMIT 1)
ORDER BY FOOD_TYPE DESC