-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, P.PRICE * O.TEMP AS SALES
FROM PRODUCT P JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TEMP
                  FROM OFFLINE_SALE
                  GROUP BY PRODUCT_ID) AS O
ON P.PRODUCT_ID=O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC