WITH SPLITED AS(
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) AS NTILED
    FROM ECOLI_DATA

)

SELECT ID, 
    CASE
        WHEN NTILED=1 THEN 'LOW'
        WHEN NTILED=2 THEN 'MEDIUM'
        WHEN NTILED=3 THEN 'HIGH'
        WHEN NTILED=4 THEN 'CRITICAL'
    END COLONY_NAME
FROM SPLITED
ORDER BY ID ASC