# -- 코드를 입력하세요
SELECT DISTINCT A.USER_ID, A.NICKNAME,
CONCAT(A.CITY,' ', A.STREET_ADDRESS1, ' ',A.STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(A.TLNO,3),'-',MID(A.TLNO,4,4),'-',RIGHT(A.TLNO,4)) AS 전화번호
FROM USED_GOODS_USER A JOIN USED_GOODS_BOARD B
ON A.USER_ID = B.WRITER_ID
WHERE A.USER_ID IN (SELECT WRITER_ID
                 FROM USED_GOODS_BOARD 
                 GROUP BY WRITER_ID
                 HAVING COUNT(*)>=3)
ORDER BY A.USER_ID DESC

