-- 코드를 입력하세요
SELECT DISTINCT CAR_ID,
    CASE
        WHEN CAR_ID IN (SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                        WHERE DATEDIFF('2022-10-16', START_DATE)>=0 AND DATEDIFF(END_DATE, '2022-10-16')>=0) THEN '대여중'
    ELSE '대여 가능'
    END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
ORDER BY CAR_ID DESC
