-- 코드를 입력하세요
WITH TEMP1 AS(
    SELECT DISTINCT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021-%'
) ,TEMP2 AS (
    SELECT COUNT(*) AS CNT
    FROM TEMP1
), TEMP3 AS(
    SELECT DISTINCT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, USER_ID
    FROM ONLINE_SALE B
    WHERE SALES_DATE LIKE '2022-%'
    AND USER_ID IN ( SELECT *
                    FROM TEMP1
    )
)

SELECT YEAR, MONTH, COUNT(*) PURCHASED_USERS, ROUND(COUNT(*)/(SELECT *
                                                             FROM TEMP2), 1) PUCHASED_RATIO
FROM TEMP3
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH