WITH RECURSIVE PARENT AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, B.GENERATION+1 AS GENERATION
    FROM ECOLI_DATA A JOIN PARENT B
    ON A.PARENT_ID = B.ID

)

SELECT COUNT(*), GENERATION
FROM PARENT
WHERE ID NOT IN (SELECT PARENT_ID
                FROM ECOLI_DATA 
                WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION