WITH TOTAL_SALES AS (
    SELECT BOOK_ID,SUM(SALES) TOTAL
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID)

-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.TOTAL*A.PRICE) AS SALES
FROM BOOK A JOIN AUTHOR B JOIN TOTAL_SALES C
ON A.AUTHOR_ID=B.AUTHOR_ID AND A.BOOK_ID=C.BOOK_ID
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC