-- 코드를 입력하세요
SELECT C.APNT_NO, A.PT_NAME, C.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM DOCTOR B JOIN APPOINTMENT C
ON B.DR_ID = C.MDDR_ID
JOIN PATIENT A
ON A.PT_NO=C.PT_NO
WHERE DATE_FORMAT(C.APNT_YMD,"%Y-%m-%d")='2022-04-13' AND C.MCDP_CD='CS'
AND C.APNT_CNCL_YN='N'
ORDER BY C.APNT_YMD