WITH RANKED AS (
    SELECT NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS ROAD, ID,PARENT_ID,SIZE_OF_COLONY,DIFFERENTIATION_DATE,GENOTYPE
    FROM ECOLI_DATA
)

SELECT ID, 
    CASE
        WHEN ROAD=1 THEN 'CRITICAL'
        WHEN ROAD=2 THEN 'HIGH'
        WHEN ROAD=3 THEN 'MEDIUM'
        ELSE 'LOW'
    END COLONY_NAME
FROM RANKED 
ORDER BY ID ASC