WITH TOTAL_HISTORY AS (
SELECT B.history_id,DAILY_FEE, DATEDIFF(end_date, start_date)+1 AS DATES
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID=B.CAR_ID
WHERE A.CAR_TYPE = '트럭'
),
DISCOUNT_TABLE AS(
SELECT DURATION_TYPE, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE='트럭'
)

SELECT history_id,
    CASE
        WHEN DATES>=90 THEN DAILY_FEE/100*(100-(SELECT DISCOUNT_RATE
                                        FROM DISCOUNT_TABLE 
                                     WHERE DURATION_TYPE='90일 이상'))*DATES
        WHEN DATES>=30 THEN DAILY_FEE/100*(100-(SELECT DISCOUNT_RATE
                                        FROM DISCOUNT_TABLE 
                                     WHERE DURATION_TYPE='30일 이상'))*DATES
        WHEN DATES>=7 THEN DAILY_FEE/100*(100-(SELECT DISCOUNT_RATE
                                        FROM DISCOUNT_TABLE 
                                     WHERE DURATION_TYPE='7일 이상'))*DATES
        ELSE DAILY_FEE*DATES
    END AS FEE
FROM TOTAL_HISTORY
ORDER BY FEE DESC, history_id DESC