WITH MONEY AS (
    SELECT DEPT_ID, ROUND(AVG(SAL),0) AVG_MONEY
    FROM HR_EMPLOYEES 
    GROUP BY DEPT_ID
)

SELECT D.DEPT_ID, D.DEPT_NAME_EN, AVG_MONEY AVG_SAL
FROM HR_DEPARTMENT D JOIN MONEY M
ON D.DEPT_ID = M. DEPT_ID
ORDER BY AVG_SAL DESC