-- 코드를 작성해주세요
WITH FRONT_END AS(
    SELECT SUM(CODE) CODE
    FROM SKILLCODES 
    WHERE CATEGORY='Front End'
),
BACK_END AS(
    SELECT SUM(CODE) CODE
    FROM SKILLCODES 
    WHERE NAME='Python'
),
C_SHOP AS(
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME='C#'
)


SELECT *
FROM(
SELECT 
    CASE
        WHEN SKILL_CODE&(SELECT CODE FROM FRONT_END) >0 AND SKILL_CODE&(SELECT CODE FROM BACK_END) >0 THEN 'A'      
        WHEN SKILL_CODE&(SELECT CODE FROM C_SHOP) >0 THEN 'B'   
        WHEN SKILL_CODE&(SELECT CODE FROM FRONT_END) >0 THEN 'C'   
        ELSE NULL
    END AS GRADE
, ID, EMAIL
FROM DEVELOPERS 
ORDER BY GRADE ASC , ID ASC) A
WHERE GRADE IS NOT NULL