WITH FRONT_END AS (
    SELECT SUM(CODE) AS CODES
    FROM SKILLCODES 
    WHERE CATEGORY='Front End'
), BACK_END AS (
    SELECT SUM(CODE) AS CODES
    FROM SKILLCODES 
    WHERE CATEGORY='Back End'
), Python AS (
    SELECT SUM(CODE) AS CODES
    FROM SKILLCODES 
    WHERE NAME='Python'
), C_SHOP AS (
    SELECT SUM(CODE) AS CODES
    FROM SKILLCODES 
    WHERE NAME='C#'
), RESULT AS(
SELECT 
    CASE
        WHEN (SKILL_CODE & (SELECT CODES
                    FROM FRONT_END)!=0) AND
            (SKILL_CODE & (SELECT CODES
                    FROM Python)!=0)
            THEN 'A'
        WHEN SKILL_CODE & (SELECT CODES
                    FROM C_SHOP)!=0
            THEN 'B'
        WHEN SKILL_CODE & (SELECT CODES
                    FROM FRONT_END)!=0
            THEN 'C'
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS   
ORDER BY GRADE, ID
)

SELECT *
FROM RESULT
WHERE GRADE IS NOT NULL