SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO A JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE LENGTH =(
        SELECT MAX(LENGTH)
        FROM FISH_INFO C
        WHERE A.FISH_TYPE = C.FISH_TYPE
)
ORDER BY ID