-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO 
WHERE REST_ID IN(
SELECT A.REST_ID
FROM(SELECT RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANKED, REST_ID
    FROM REST_INFO ) AS A
WHERE A.RANKED = 1)
ORDER BY FOOD_TYPE DESC
