-- 코드를 작성해주세요

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO A LEFT JOIN FISH_NAME_INFO C
ON A.FISH_TYPE=C.FISH_TYPE
WHERE ID= (SELECT ID
          FROM FISH_INFO B
          WHERE A.FISH_TYPE=B.FISH_TYPE
          ORDER BY LENGTH DESC
          LIMIT 1)
ORDER BY ID