-- 코드를 입력하세요
SELECT K.ANIMAL_ID, K.NAME
FROM (
SELECT I.ANIMAL_ID, O.NAME, I.DATETIME START, O.DATETIME END, DATEDIFF(O.DATETIME, I.DATETIME) AS DIFF
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
ON (I.ANIMAL_ID = O.ANIMAL_ID)
WHERE O.DATETIME IS NOT NULL
ORDER BY DIFF DESC
LIMIT 2) AS K
