WITH RECURSIVE PARENT AS (
    SELECT ID, 1 AS LEVEL
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT SON.ID, PARENT.LEVEL+1
    FROM ECOLI_DATA SON JOIN PARENT
    ON SON.PARENT_ID=PARENT.ID
)

SELECT ID
FROM PARENT
WHERE LEVEL = 3
ORDER BY ID ASC