-- 코드를 입력하세요
WITH HAHA AS(
SELECT PRODUCT_NAME, CATEGORY,PRICE, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS HI
FROM FOOD_PRODUCT 
)

SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
FROM HAHA
WHERE HI='1' AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC